# Travis file for running some basic set of testreport checks on each commit
language: python

# services: 
#  - docker

before_install:
  - test -n $CC && unset CC
  #  Set up environment needed for Sphinx to build docs
  - sudo apt-get install texlive-latex-recommended
  - sudo apt-get install texlive-latex-extra
  - sudo apt-get install texlive-fonts-recommended
  - sudo apt-get install latexmk
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install sphinxcontrib-bibtex
    # Set up environment needed to run testreport code tests
  # - docker pull mitgcm/testreport-images:fc11-base-20170715
  # - docker run  -v `pwd`:/MITgcm --name fc11-testreport -t -d mitgcm/testreport-images:fc11-base-20170715 /bin/bash
  # - docker exec -i fc11-testreport rpm -vv --rebuilddb
  # - docker exec -i fc11-testreport df -h
  # - docker exec -i fc11-testreport ls -altr /MITgcm
  - sudo apt-get install gcc
  - sudo apt-get install gfortran
  # - sudo apt-get install netcdf-bin
  # - sudo apt-get install libnetcdff5
  - pip install argparse
  - sudo apt-get install mpich
  - sudo apt-get install libmpich-dev
  # set options for Travis script
  - echo `pwd`
  - export MITGCM_TROPT="-devel"
  # -of=../tools/build_options/linux_amd64_gfortran"
  # - export MITGCM_DECMD="docker exec -i fc11-testreport bash -c"
  - export MITGCM_DECMD=""

jobs:
  include:
    # run the tests
    - stage: code tests
      env: 
      - MITGCM_EXP="aim.5l_cs" MITGCM_PRECS="14 16"
      script: 
      - cd verification; ./testreport -t ${MITGCM_EXP} ${MITGCM_TROPT} | tee ${MITGCM_EXP}/testreport_out.txt
      - python verification_parser.py -filename ${MITGCM_EXP}/testreport_out.txt -threshold ${MITGCM_PRECS}
    - env:
      - MITGCM_EXP="global_ocean.90x40x15"
      - MITGCM_PRECS="16 16 16"
      script: 
      - export MITGCM_TROPT="-devel -MPI 5" 
      - cd verification; ./testreport -t ${MITGCM_EXP} ${MITGCM_TROPT} | tee ${MITGCM_EXP}/testreport_out.txt
      - python verification_parser.py -filename ${MITGCM_EXP}/testreport_out.txt -threshold ${MITGCM_PRECS}
    - env:
      - MITGCM_EXP="global_ocean.cs32x15" MITGCM_PRECS="16 16 16 16 16"
      script: 
      - cd verification; ./testreport -t ${MITGCM_EXP} ${MITGCM_TROPT} | tee ${MITGCM_EXP}/testreport_out.txt
      - python verification_parser.py -filename ${MITGCM_EXP}/testreport_out.txt -threshold ${MITGCM_PRECS}
    - env: 
      - MITGCM_EXP="hs94.cs-32x32x5" MITGCM_PRECS="13 16"
      script: 
      - cd verification; ./testreport -t ${MITGCM_EXP} ${MITGCM_TROPT} | tee ${MITGCM_EXP}/testreport_out.txt
      - python verification_parser.py -filename ${MITGCM_EXP}/testreport_out.txt -threshold ${MITGCM_PRECS}
    - env: 
      - MITGCM_EXP="isomip" MITGCM_PRECS="16 16 16"
      script: 
      - cd verification; ./testreport -t ${MITGCM_EXP} ${MITGCM_TROPT} | tee ${MITGCM_EXP}/testreport_out.txt
      - python verification_parser.py -filename ${MITGCM_EXP}/testreport_out.txt -threshold ${MITGCM_PRECS}
    - env: 
      - MITGCM_EXP="offline_exf_seaice" MITGCM_PRECS="16 16 16 16 16"
      script: 
      - cd verification; ./testreport -t ${MITGCM_EXP} ${MITGCM_TROPT} | tee ${MITGCM_EXP}/testreport_out.txt
      - python verification_parser.py -filename ${MITGCM_EXP}/testreport_out.txt -threshold ${MITGCM_PRECS}
    - env: 
      - MITGCM_EXP="tutorial_advection_in_gyre" MITGCM_PRECS="16"
      script: 
      - cd verification; ./testreport -t ${MITGCM_EXP} ${MITGCM_TROPT} | tee ${MITGCM_EXP}/testreport_out.txt
      - python verification_parser.py -filename ${MITGCM_EXP}/testreport_out.txt -threshold ${MITGCM_PRECS}
    - env: 
      - MITGCM_EXP="tutorial_cfc_offline" MITGCM_PRECS="16"
      script: 
      - cd verification; ./testreport -t ${MITGCM_EXP} ${MITGCM_TROPT} | tee ${MITGCM_EXP}/testreport_out.txt
      - python verification_parser.py -filename ${MITGCM_EXP}/testreport_out.txt -threshold ${MITGCM_PRECS}
    - env: 
      - MITGCM_EXP="tutorial_deep_convection" MITGCM_PRECS="16 16"
      script: 
      - cd verification; ./testreport -t ${MITGCM_EXP} ${MITGCM_TROPT} | tee ${MITGCM_EXP}/testreport_out.txt
      - python verification_parser.py -filename ${MITGCM_EXP}/testreport_out.txt -threshold ${MITGCM_PRECS}
    - env: 
      - MITGCM_EXP="tutorial_global_oce_biogeo" MITGCM_PRECS="16"
      script: 
      - cd verification; ./testreport -t ${MITGCM_EXP} ${MITGCM_TROPT} | tee ${MITGCM_EXP}/testreport_out.txt
      - python verification_parser.py -filename ${MITGCM_EXP}/testreport_out.txt -threshold ${MITGCM_PRECS}
    - env: 
      - MITGCM_EXP="tutorial_global_oce_in_p" MITGCM_PRECS="16"
      script: 
      - cd verification; ./testreport -t ${MITGCM_EXP} ${MITGCM_TROPT} | tee ${MITGCM_EXP}/testreport_out.txt
      - python verification_parser.py -filename ${MITGCM_EXP}/testreport_out.txt -threshold ${MITGCM_PRECS}
    - env: 
      - MITGCM_EXP="tutorial_plume_on_slope" MITGCM_PRECS="16"
      script: 
      - cd verification; ./testreport -t ${MITGCM_EXP} ${MITGCM_TROPT} | tee ${MITGCM_EXP}/testreport_out.txt
      - python verification_parser.py -filename ${MITGCM_EXP}/testreport_out.txt -threshold ${MITGCM_PRECS}
    # - stage: summary of code tests
    # disabled because jobs do not share data
    # Generate a summary
    #  script: docker exec -i fc11-testreport bash -c "cd /MITgcm/verification; ./testreport ${MITGCM_TROPT} -q"
    # build documentation
    - stage: test documentation
      env: 
      - BUILD="html"
      script: cd doc; make clean ${BUILD}
    - env:
      - BUILD="latexpdf"
      script: cd doc; make clean ${BUILD}
